In [55]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from scipy.special import softmax

from sklearn.model_selection import train_test_split
from sklearn.metrics import multilabel_confusion_matrix

import os

basepath_1 = 'C:\Academic\ECE - 4370 (Machine_Learning)\Assignments\Assignment_4\Celegans_ModelGen/1'
labelled_images = []
for image in os.listdir(basepath_1):
    if os.path.isfile(os.path.join(basepath_1, image)):
        img = mpimg.imread(os.path.join(basepath_1, image))
        # remove line below to insert 101x101 images
        arr_img = img.reshape([10201])
        arr_img = np.hstack((arr_img, 1))
        labelled_images.append(arr_img)
        
basepath_0 = 'C:\Academic\ECE - 4370 (Machine_Learning)\Assignments\Assignment_4\Celegans_ModelGen/0'
for image in os.listdir(basepath_0):
    if os.path.isfile(os.path.join(basepath_0, image)):
        img = mpimg.imread(os.path.join(basepath_0, image))
        arr_img = img.reshape([10201])
        arr_img = np.hstack((arr_img, 0))
        labelled_images.append(arr_img)
np.random.shuffle(labelled_images)
# W is (M+1)xK -> 2x2
W = np.random.randn(10201+1,2)

In [56]:
m = W.shape[0] - 1
k = W.shape[1]
t = np.zeros((1, k))
for image in labelled_images:
    target = np.zeros(k)
    label = image[-1]
    target[int(label)] = 1
    t = np.vstack((t, target))
t = np.delete(t, 0, axis=0)

In [57]:
x = []
for image in labelled_images:
    image = np.delete(image, -1, axis=0)
    x.append(image)


In [58]:
x = np.array(x).reshape(len(x), 10201)
x = np.hstack((x, np.ones((len(x), 1))))

In [59]:
X_train, X_test, Y_train, Y_test = train_test_split(mnist_data_normalized, mnist_label, test_size=0.20, random_state=42)

(11000, 10202)

In [71]:
phi = 0.0001
max_iter = 10000
n = x.shape[0] # num samples
m = x.shape[1] # num measurements per sample
k = W.shape[1] # num classes
for _ in range(max_iter):
    # error = -(1 / m) * (np.dot(t.T, np.log(y)) + np.dot((1 - t).T, np.log(1 - y)))
    a = np.dot(x, W)
    y = softmax(a, axis=1)
    for j in range(k):
        sum_error_gradient = 0
        """ for i in range(n):
            sum_error_gradient = sum_error_gradient + np.dot((y[i][j] - t[i][j]), x[i]) """
        sum_error_gradient = np.dot((y[:,j] - t[:,j]), x)
        error = sum_error_gradient.reshape(10202,1)
        W[:, j:j+1] = W[:, j:j+1] - (phi * error)

In [61]:
y[:,0].shape

(11000,)

In [72]:
W

array([[  6.94708697,  -4.86543632],
       [  5.19622449,  -6.87663212],
       [  3.86302956,  -4.375083  ],
       ...,
       [ -3.05194943,   3.91039999],
       [ -2.58991169,   3.84712369],
       [ 11.24406037, -10.78290008]])

In [73]:
df_w = pd.DataFrame(W)
df_w.to_csv("weights.csv")

In [74]:
y = softmax(np.dot(x, W), axis=1)

In [75]:
y_pred = np.array([9,9])
for preds in y:
    index = np.argmax(preds)
    arr = np.zeros(len(preds))
    arr[index] = 1
    y_pred = np.vstack((y_pred, arr))
y_pred = np.delete(y_pred, 0, axis=0)

In [76]:
# this should be very close to t
y_pred

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [77]:
cf_matrix = multilabel_confusion_matrix(t, y_pred, labels=[False, True])
print(cf_matrix)

[[[1159 4341]
  [ 509 4991]]

 [[4991  509]
  [4341 1159]]]


In [78]:
correct = 0
for i, preds in enumerate(y_pred):
    if np.array_equal(preds, t[i]):
        correct += 1

In [79]:
correct / 11000
       

0.5590909090909091

In [70]:
# X is Nx(M+1) -> Nx2 
# used to test logistic regression implementation
""" df = pd.read_csv("C:\Developer\ML_PR\ML\logistic_regression\classification.csv")
x = df.iloc[:,:-1]
x = np.hstack((x, np.ones((x.shape[0],1))))
# fix t to make it one-hot encoded
classes = df.loc[:,'success'].astype('int64') """

""" 
for test in classes:
    if test:
        t = np.vstack((t, [1, 0]))
    else:
        t = np.vstack((t, [0, 1]))
t = np.delete(t, 0, axis=0) """

' \nfor test in classes:\n    if test:\n        t = np.vstack((t, [1, 0]))\n    else:\n        t = np.vstack((t, [0, 1]))\nt = np.delete(t, 0, axis=0) '